### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by beruhdejene** [tabdelaal/CyTOFmerge#2]
Hi @tabdelaal 

I was just wondering, do I need to create separate " RelevantMarkers1" and "RelevantMarkers2" files (.csv or something)?

**Comment by tabdelaal** [comment]
Hi @beruhdejene ,

RelevantMarkers1 and RelevantMarkers2 are integer arrays indicating the markers (columns) indices to be used from FCSfile1 and FCSfile2, respectively. 

For example, if FCSfile1 contains this channel list in order [Time, Event_Length, CD45, CD3, CD4, Residual], and for merging you only want to use your protein markers CD45, CD3 and CD4. Then, RelevantMarkers1 should be [3,4,5] indicating the location of these 3 markers within the columns of FCSfile1.

Hope it's more clear now.

**Comment by beruhdejene** [comment]
Hi @tabdelaal,

It worked. Thanks, that makes sense now.
